# Generated by Django 2.2.3 on 2019-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_id', models.CharField(default='', max_length=50)),
                ('product_ID1', models.CharField(default='', max_length=50)),
                ('product_ID2', models.CharField(blank=True, default='', max_length=50)),
                ('product_ID3', models.CharField(blank=True, default='', max_length=50)),
                ('product_ID4', models.CharField(blank=True, default='', max_length=50)),
                ('product_ID5', models.CharField(blank=True, default='', max_length=50)),
                ('product_ID6', models.CharField(blank=True, default='', max_length=50)),
                ('product_ID7', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
