# Generated by Django 2.2.3 on 2019-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picklistdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='product_ID10',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='picklist',
            name='product_ID8',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='picklist',
            name='product_ID9',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
