# Generated by Django 2.2.3 on 2019-07-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(default='', max_length=50)),
                ('region', models.CharField(choices=[('NA', 'NA'), ('SEA', 'SEA'), ('EUR', 'Europe'), ('ASIA', 'ASIA'), ('CHINA', 'CHINA')], max_length=50)),
                ('city_ID', models.IntegerField()),
                ('target', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('company', models.CharField(default='Amazon', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.BaseClass')),
            ],
        ),
        migrations.CreateModel(
            name='Asus',
            fields=[
                ('company', models.CharField(default='Asus', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.BaseClass')),
            ],
        ),
        migrations.CreateModel(
            name='Intel',
            fields=[
                ('company', models.CharField(default='Intel', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.BaseClass')),
            ],
        ),
    ]
