# Generated by Django 2.2.3 on 2019-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190730_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asus',
            name='information',
        ),
        migrations.RemoveField(
            model_name='intel',
            name='information',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='company',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Intel', 'Intel'), ('Asus', 'Asus')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Amazon',
        ),
        migrations.DeleteModel(
            name='Asus',
        ),
        migrations.DeleteModel(
            name='Intel',
        ),
    ]
