# Generated by Django 2.2.3 on 2019-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190730_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclass',
            name='city_ID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
